# Generated by Django 3.1.6 on 2021-02-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
