# Generated by Django 3.1.6 on 2021-03-02 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210301_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='watchlists_l', to='auctions.Listing'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watcher',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watcher',
            field=models.ManyToManyField(blank=True, related_name='watchlists_w', to=settings.AUTH_USER_MODEL),
        ),
    ]
