# Generated by Django 3.1.6 on 2021-03-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210302_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watcher',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watcher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists_w', to='auctions.user'),
            preserve_default=False,
        ),
    ]
