# Generated by Django 3.1.6 on 2021-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkext', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='networkext.Post'),
        ),
    ]
